### ISSUE TITLE
Leaks

### ISSUE THREAD

**Issue by Maan2003** [noib3/nvim-oxi#15]
Currently, once a `Object`(string, array, ...) is created it is *never* freed. `Object`, `String` `Collection` don't implement drop. We need to be more systematic about it.

**Comment by Maan2003** [comment]
Looking at neovim source code, I concluded that all `nvim_*` api functions just borrow the arguments for **the duration of the call**. The caller owns the the arguments and return value.

based on:
1. [msgpack freeing the arguments](https://sourcegraph.com/github.com/neovim/neovim@9745941ef620da86bf18f965f85e8fc2ce8206b5/-/blob/src/nvim/msgpack_rpc/channel.c?L349)
2. [msgpack freeing the return value](https://sourcegraph.com/github.com/neovim/neovim@9745941ef620da86bf18f965f85e8fc2ce8206b5/-/blob/src/nvim/msgpack_rpc/channel.c?L345)

**Comment by noib3** [comment]
>  We need to be more systematic about it.

Yes, definitely. The current implementation [is commented out](https://github.com/noib3/nvim-oxi/blob/b523488d14bea12c887404e719cf2431e9417766/nvim-types/src/object.rs#L150) because it was causing an error [here](https://github.com/noib3/nvim-oxi/blob/b523488d14bea12c887404e719cf2431e9417766/nvim-types/src/object.rs#L393). I still haven't looked into how to do it properly, but you can have a try at it if you want. Btw, wrapping those values in `ManuallyDrop` may not be necessary.

**Comment by noib3** [comment]
fixed in #27

**Comment by airblast-dev** [comment]
I think this issue is still valid. Created Strings are not freed based on the Drop impl.

The PR with the Drop changes mentioned above seems to be partially reverted(?) in https://github.com/noib3/nvim-oxi/commit/3f75ed9eee00ea03bae07e059b3dddc0d90f7395.

Minimally a doc comment should be added mentioning the leaking situation, and ideally it should be fixed. 
While I did find the commit that this was reverted, I wasn't able to find out why.

I am open to working on this, but it would be nice to know why this change was reverted in the first place.
I also checked other allocation such as `Array` and they seem to be freed as normal. Not sure what is the case here.
