### ISSUE TITLE
NvimError("\'ctermbg\' must be string or integer")',

### ISSUE THREAD

**Issue by luxus** [noib3/nvim-oxi#53]
when i try to compile the plugin with nyoom 
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NvimError("\'ctermbg\' must be string or integer")', /Users/luxus/.cargo/git/checkouts/nvim-oxi-68d2fdc1d1cdbe82/15fb30d/nvim-oxi/src/lua/lua.rs:41:12
stack backtrace:
   0:        0x103ecf8a0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he13a97dfe3ba6dc4
   1:        0x103ef73e4 - core::fmt::write::hd751207b60c12d4c
   2:        0x103ed9954 - std::io::Write::write_fmt::h08841cca3656c74a
   3:        0x103ee4404 - std::panicking::default_hook::{{closure}}::h8d96478a0c41fbb8
   4:        0x103ee40c8 - std::panicking::default_hook::haca5b586a55289c5
   5:        0x103ee4918 - std::panicking::rust_panic_with_hook::h419d889b0a87beff
   6:        0x103ecfcfc - std::panicking::begin_panic_handler::{{closure}}::hf9a5ae5699838d81
   7:        0x103ecf9b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h6248404e1e92c641
   8:        0x103ee4518 - _rust_begin_unwind
   9:        0x103efb92c - core::panicking::panic_fmt::ha964b6658f104372
  10:        0x103efb988 - core::result::unwrap_failed::hf92687bbd06849b8
  11:        0x103ec9334 - _luaopen_oxocarbon
  12:        0x101246258 - <unknown>
  13:        0x1012be51c - _luaL_openlibs
  14:        0x101246258 - <unknown>
  15:        0x10125995c - _lua_pcall
  16:        0x100cdbdc4 - _nlua_require
  17:        0x101246258 - <unknown>
  18:        0x10125995c - _lua_pcall
  19:        0x100cd94bc - _nlua_pcall
  20:        0x100cda3a8 - _nlua_exec_file
  21:        0x100db0fa0 - _do_source
  22:        0x100dadbbc - _do_in_cached_path
  23:        0x100dad140 - _source_runtime
  24:        0x100cbc97c - _load_colors
  25:        0x100c81ba4 - _ex_colorscheme
  26:        0x100c7d33c - _execute_cmd0
  27:        0x100c7d050 - _execute_cmd
  28:        0x100bce964 - _nvim_cmd
  29:        0x100bbc2f0 - _nlua_api_nvim_cmd
  30:        0x101246258 - <unknown>
  31:        0x1012be51c - _luaL_openlibs
  32:        0x101246258 - <unknown>
  33:        0x10125995c - _lua_pcall
  34:        0x100cdbdc4 - _nlua_require
  35:        0x101246258 - <unknown>
  36:        0x1012be51c - _luaL_openlibs
  37:        0x101246258 - <unknown>
  38:        0x10125995c - _lua_pcall
  39:        0x100cdbdc4 - _nlua_require
  40:        0x101246258 - <unknown>
  41:        0x10125995c - _lua_pcall
  42:        0x100cd94bc - _nlua_pcall
  43:        0x100cda3a8 - _nlua_exec_file
  44:        0x100db0fa0 - _do_source
  45:        0x100ce3344 - _main
fatal runtime error: Rust panics must be rethrown
fish: Job 1, 'RUST_BACKTRACE=full bin/nyoom...' terminated by signal SIGABRT (Abort)
```

```
rustc --version
rustc 1.62.1

cargo --version
cargo 1.62.0
```

**Comment by noib3** [comment]
By briefly looking at the linked issue it seems the problem is with `oxocarbon.nvim`? If you could provide a code snippet replicating the failure that'd be great, not really sure what that plugin is doing. Also, is it compiling `nvim-oxi` with or without the `nightly` feature flag?

**Comment by NachiketNamjoshi** [comment]
I'm guessing its this:

https://github.com/shaunsingh/oxocarbon.nvim/blob/main/src/lib.rs#L33

Noob guess: `set background=dark/light` should not cause it to panic?

I may be wrong. @noib3 can you check it out?

**Comment by luxus** [comment]
sorry for not delivering all infos at the beginning
https://github.com/shaunsingh/nyoom.nvim/blob/main/bin/nyoom
is the script that build the config ... first `bin/nyoom install` and then `bin/nyoom sync`
when i try to start nvim then it shows the error 
i only found ctermbg in oxi and not in the theme, thats why i thought its not the theme itself. 

it used to work and break since some newer versions of rust 
i tested it on linux and mac with multiple versions of rust

there are multiple people with the issue since some days 
https://github.com/shaunsingh/oxocarbon.nvim/issues/9

**Comment by noib3** [comment]
@luxus I get all that, but if I was opening an issue on someone else's project I'd at least give them a code example that replicates the error. I might be wrong but it sounds like you're asking me to debug that shell script, which I don't think is a reasonable request.

Once I have a code snippet that I can use to figure out what the error might be then I'll be happy to help.

**Comment by luxus** [comment]
looks like the problem is indeed not the theme or the simple script itself.. 
https://github.com/noib3/nvim-oxi/runs/7926368174?check_suite_focus=true complaining about foreground color as well
i closed the issue, don't think i can help here.

**Comment by noib3** [comment]
@luxus the error messages are clearly different: `'ctermbg' must be string or integer` vs `'foreground' must be string or integer`. And I still have no idea what code is causing the error you reported.

**Comment by noib3** [comment]
should be fixed in 7aa9521b1ab4998ad26192615475812e8ba95507

**Comment by luxus** [comment]
i tested it with an older commit that used oxi, still the same error message.
by now the other of the config moved away from nvim-oxi, so for me it's not that important to fix the issue.. maybe it was a theme issue and not related to nvim-oxi

what i did to test it.
i did a backup of my config
then
````sh
rm -rf ~/.cargo; rm -rf ~/.config/nvim; rm -rf ~/.local/share/nvim
git clone git@github.com:shaunsingh/nyoom.nvim.git ~/.config/nvim
cd ~/.config/nvim
git checkout 4cb9e18
bin/nyoom install
bin/nyoom sync
nvim
````

**Comment by noib3** [comment]
That's expected, if you checkout an older commit of that project then `oxocarbon.nvim` will still use an older version of `nvim-oxi`.

You should clone `oxocarbon.nvim`, do a `cargo update` to update the `nvim-oxi` dependency to the latest master and use that version of `oxocarbon.nvim` in `nyoom` (or don't use `nyoom` at all, AFAICS the issue is with `oxocarbon` and has nothing to do w/ `nyoom`).
